### ISSUE TITLE
Check for API version in Unbind operation

### ISSUE THREAD

**Issue by desislavaa** [pivotal-cf/brokerapi#102]
Hello all,

There is [this check](https://github.com/pivotal-cf/brokerapi/blob/447a19ef11305d60c9b9eaa91497743ec5c7a572/handlers/unbind.go#L30) for API version > 2.14 for async unbind operations which fails the request when  `accepts_incomplete` is `true`. 

`accepts_incomplete` is not supported in versions <14, so I understand the point of the check.
However, in my use case, the broker is now deployed on K8S and the Service Catalog sends an async request with API version header `2.13`. The service catalog uses the `kubernetes-sigs/go-open-service-broker-client` package and [here](https://github.com/kubernetes-sigs/service-catalog/blob/52979db81ee020a18f1aabda837d350c713ad0ba/pkg/controller/controller.go#L1277) we can see it uses the default configuration of the client lib, where the [latest API version is 2.13](https://github.com/kubernetes-sigs/service-catalog/blob/master/vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/version.go#L43).

I've also noticed that the check is not executed for deprovision, which is inconsistent.

What do you think about removing the check for now and rely more on the value passed as `accepts_incomplete`? If you agree, I can make the PR.

**Comment by FelisiaM** [comment]
Hi @desislavaa 

Sorry for the delay - We removed the check and will be releasing soon

Thanks
Felisia & @kirederik
