### ISSUE TITLE
Missing metadata field in ProvisionedServiceSpec

### ISSUE THREAD

**Issue by jasiu001** [pivotal-cf/brokerapi#128]
Hi, 

According to [OSB API](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-4), we should be allowed to return the metadata field in a provisioning response. 
Do you plan to update [`ProvisionedServiceSpec`](https://github.com/pivotal-cf/brokerapi/blob/main/v7/domain/service_broker.go#L92) struct in the near future?

If no, then we can make a contribution, but to be honest, we really need this fast so my second question will be: there is a chance all processes from your side about the review and merge will be quick?

**Comment by FelisiaM** [comment]
Hi @jasiu001 

This is a property introduced in OSBAPI 2.16 and we haven't started working on that yet.
WE are not doing much active development here at the movement but we would be happy to review your PR and merge it asap 🙂

As a side note, it would be interesting to know what is your use case for returning metadata on provision and what platform would be using that?

Thanks,
Felisia

**Comment by jasiu001** [comment]
Hi @FelisiaM 

That is great, I made [PR](https://github.com/pivotal-cf/brokerapi/pull/131) with implementation.

We use your library in our open-source [Kyma](https://github.com/kyma-project/kyma) project, to be more specific in the [system](https://github.com/kyma-project/control-plane) which installs clusters with Kyma.
External services trigger provisioning using OSB API and your library is really helpful to handle this :)

**Comment by FelisiaM** [comment]
Thank you for your contribution @jasiu001 

I have now merged the PR and released version 7.5.0 with the change
