### ISSUE TITLE
Missing allow_context_updates field

### ISSUE THREAD

**Issue by piotrmiskiewicz** [pivotal-cf/brokerapi#130]
According to OSB API Spec, the Service Offering Object contains an allow_context_updates which is missing in the current implementation. The flag was introduces in OSB API 2.15.

The PR which adds the field: https://github.com/pivotal-cf/brokerapi/pull/129

**Comment by FelisiaM** [comment]
Hi @piotrmiskiewicz 

Thanks for raising this and submitting a PR.

It looks like the PR is making a change in the v7 folder rather that the code and the tests themselves.
Would you mind making the change in the `domain/service_catalog.go` and updating the corresponding test?

Thanks,
Felisia

**Comment by piotrmiskiewicz** [comment]
hi, yes, I'll do. So I have a question - what is the purpose having the v7 folder?

**Comment by piotrmiskiewicz** [comment]
Next question: should I modify v7/domain and domain/ or only domain/ ?

**Comment by FelisiaM** [comment]
We usually run a script to make sure that v7 has all the right files. In effect that would copy your changes into v7 folder. 
For this change, you can leave the change in v7 since its already commited.

**Comment by piotrmiskiewicz** [comment]
I've updated the PR: https://github.com/pivotal-cf/brokerapi/pull/129

**Comment by FelisiaM** [comment]
Thank you! I have now merged the PR.
