### ISSUE TITLE
Support for updating service instances

### ISSUE THREAD

**Issue by ldmberman** [pivotal-cf/brokerapi#14]
Hi,

I am going to work on adding support for [updating service instances](http://docs.cloudfoundry.org/services/api.html#updating_service_instance). From the start, I would like to discuss things to be sure I keep following the right direction.

These are the public-facing changes  I am going to make:

* Update `brokerapi.Service` with a `PlanUpdatable` field:
```
    ...
    PlanUpdatable bool `json:"plan_updateable"`
```

* Extend `ServiceBroker` with an `Update` method:
```
    ...
    Update(instanceID string, details UpdateDetails, asyncAllowed bool) (IsAsync, error)
```

* With `UpdateDetails` declared as:
```
type UpdateDetails struct {
    ServiceID string `json:"service_id"`
    PlanID string `json:"plan_id"`
    Parameters map[string]interface{} `json:"parameters"`
}
```

Both the public-facing part and the work to be done under the hood seem very similar to what is done for instance provisioning, and I do not expect to encounter any pitfalls for now.

Looking for your thoughts.

**Comment by craigfurman** [comment]
Hi @ldmberman, it turns out we recently [committed exactly the same thing](https://github.com/pivotal-cf/brokerapi/commit/92069d5b1483d85ef170328093404b9176f03a4d).

**Comment by ldmberman** [comment]
Anyway, thank you for pushing this work forward.
