### ISSUE TITLE
Is the FailureResponse status code used?

### ISSUE THREAD

**Issue by renier** [pivotal-cf/brokerapi#162]
I ask because I have an implementation like this:

```go
func (f *serviceBroker) Services(ctx context.Context) ([]domain.Service, error) {
	return nil, apiresponses.NewFailureResponse(errors.New("TODO"), http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented)) // TODO: Implement
}
```

but going to `/v2/catalog` gives me this http response:
```
$> curl -i -u ":" -H "X-Broker-API-Version: 2.13" http://localhost:8080/v2/catalog
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Correlation-Id: c2g7orea0bri9krepjs0
Date: Sun, 16 May 2021 01:59:09 GMT
Content-Length: 23

{"description":"TODO"}
```
Using v8 of this module.

Based on the docs [here](https://pkg.go.dev/github.com/pivotal-cf/brokerapi/v8/domain/apiresponses#NewFailureResponse), I expected the response status code to be `501` instead.

**Comment by renier** [comment]
Yep, it's a problem specifically with the catalog handler [here](https://github.com/pivotal-cf/brokerapi/blob/v8.0.0/handlers/catalog.go#L16-L21). It should have been coded to test for a FailureResponse like [this](https://github.com/pivotal-cf/brokerapi/blob/v8.0.0/handlers/get_instance.go#L47-L49).

**Comment by FelisiaM** [comment]
Hi @renier 

Thanks for catching this. 
Would you be open to creating a PR with the change and corresponding tests for it?

Thanks,
Felisia

**Comment by renier** [comment]
@FelisiaM Ok. See #165

**Comment by FelisiaM** [comment]
Thank you for your contribution @renier! 

This change will be included in the next release in a few days.
