### ISSUE TITLE
Incorrect type for metadata fields in Get/Provision/Deprovision responses

### ISSUE THREAD

**Issue by r6q** [pivotal-cf/brokerapi#175]
I noticed in this [PR ](https://github.com/pivotal-cf/brokerapi/commit/7d156dee81f718f2d0ec14a39d823860d8ae2fdf#diff-ccfe2d00d147a7d2f00d3f53249e1f80c8449c61992f86fcbac4b9debb0bec6fR101) a new `metadata` field  (with labels/attributes) was added as per latest OSB specification. 

Is there any reason for creating labels and attributes as a `map[string]string` instead of `interface{}` as per [OSB specification](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-instance-metadata) where metadata `labels` and `attributes` fields are `object` type like `parameters` field (or at the least making it `map[string]interface{}` so integers and structs can be used as values) ?

Current implementation limits proper usage of labels and attributes of metadata in ServiceBroker implementation. I can add PR changing labels and attributes to `interface{}` (or `map[string]interface{}`) if you agree.

**Comment by FelisiaM** [comment]
Hi @r6q 

The spec defines both these fields as key-value fields, also in reality the platforms that defined the concepts and potentially make use of the labels and annotations define some more restrictions.
Regarding `labels` the concept was taken from [K8s labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) and [CF labels](http://v3-apidocs.cloudfoundry.org/version/3.69.0/index.html#metadata) and both of them define labels as key-values of strings (that can also be queriable). Given this, I would be inclined to keep it as a `map[string]string`.

The `annotations` concept was also taken from [K8s annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) and [CF annotations](http://v3-apidocs.cloudfoundry.org/version/3.69.0/index.html#metadata). They both define it as a key-value. However, CF expects the values to be a string and in K8s it can be an interface.

To keep in line with these current community definitions of `labels` and `annotations` I think it is ok to create a PR where `annotations` are defined as `map[string]interface{}`.

Thanks,
Felisia

**Comment by r6q** [comment]
Ok, thanks for your insight, let's leave it as <`string`, `string`>
