### ISSUE TITLE
why ErrInstanceAlreadyExists respond "EmptyResponse"

### ISSUE THREAD

**Issue by hank-sunday** [pivotal-cf/brokerapi#19]
if err != nil {
			switch err {
			case ErrInstanceAlreadyExists:
				logger.Error(instanceAlreadyExistsErrorKey, err)
				respond(w, http.StatusConflict, EmptyResponse{})
			case ErrInstanceLimitMet:
				logger.Error(instanceLimitReachedErrorKey, err)
				respond(w, http.StatusInternalServerError, ErrorResponse{
					Description: err.Error(),
				})

why ErrInstanceAlreadyExists does not respond detail error message like ErrInstanceLimitMet?

**Comment by spectreOfAbsorbance** [comment]
The current [broker API](http://docs.cloudfoundry.org/services/api.html#provisioning) specifies an empty JSON object body for the 409 conflict response.

Cloud controller knows that status 409 means instance already exists, and knows how to handle that situation. Custom error messages from brokers are for errors that cloud controller doesn't have handling logic for, in which case the status code 500 is used.
