### ISSUE TITLE
Setting CF labels not supported?

### ISSUE THREAD

**Issue by haraldfuchs** [pivotal-cf/brokerapi#209]
My broker has a method
```
func (esb *MyBroker) Provision(ctx context.Context, instanceID string,
	details brokerapi_domain.ProvisionDetails,
	asyncAllowed bool) (brokerapi_domain.ProvisionedServiceSpec, error)
```
which returns something like this:
```
var spec brokerapi_domain.ProvisionedServiceSpec
labels := map[string]string{"foo": "bar"}
spec.Metadata = brokerapi_domain.InstanceMetadata{Labels: labels}
return spec, nil
```
But after creating a service instance `foo`, `cf labels service-instance foo` returns nothing.

**Comment by FelisiaM** [comment]
Hi @haraldfuchs 

The addition of labels is introduced in OSBAPI v2.16 - for that to take effect both the brokers and the CF cloud controller should implement the latest spec. 

v2.16 of OSBAPI is not compatible with CF Cloud Controller API which is compatible up to version 2.15. Said differently that feature is not supported by CC API.

If you have a use case for it I would suggest raising a request in CF Cloud Controller and if that gets prioritised we can see if BrokerAPI requires any changes to be compatible with it.

Thanks,
Felisia

**Comment by haraldfuchs** [comment]
What do you mean with "that feature is not supported by CC AP"?  If I use
cf curl to talk directly to the Cloud Controller, I can create a service
instance with labels (cf curl /v3/service_instances -X POST -d '...'), and
I can add labels to an existing service instance (cf curl
/v3/service_instances/<instanceGuid> -X PATCH -d '{"metadata": {"labels":
{"foo": "bar"}}}').  Unfortunately cf curl /v3/info doesn't tell me the
version, but cf curl /v2/info says

> {
>   "api_version": "2.184.0",
>   "osbapi_version": "2.15",
>   ...
> }
>

Am Mi., 3. Aug. 2022 um 15:33 Uhr schrieb Felisia Martini <
***@***.***>:

**Comment by FelisiaM** [comment]
Hi @haraldfuchs,

There are two specified ways to assign labels to a service instance. 
1. User-defined labels that are passed from CF during creation time or after an instance has been created. So the labels should be passed from a CF request (provision/update) to the broker. These labels never reach the broker and are known only by the CC API. This is what is implemented and should be working with CC API using the CC API v3 (the endpoint you pointed out). 
2. Broker-defined labels that are assigned from the broker on provision/update time. These labels would need to be passed back to CC API and the CC API would need to record them as service instance labels. This functionality is defined in OSBAPI 2.16 but is not implemented by the CC API (The latest OSBAPI version compatible with CC API is 2.15). So even when a broker sends labels back to the CC API during a provision request the labels do not take effect. 

My understanding is that your use case is attempting to do the second option. And this is not supported by CC API at the moment. 

Let me know if you have any further questions.

Regards,
Felisia
