### ISSUE TITLE
Replace lager.Logger with log/slog.Logger

### ISSUE THREAD

**Issue by elgohr** [pivotal-cf/brokerapi#267]
### Is your feature request related to a problem? Please describe.

At the moment the brokerapi requires an import of `lager.Logger` as another third party dependency.
As the `lager.Logger` interface contains `LogFormat` in `Sink`, it can't be implemented without the dependency to lager.Logger.
I would like to avoid the dependency to another third party dependency.

### Describe the solution you'd like

Replace `lager.Logger` with an own interface or use `log/slog.Logger` as a solution from the standard library.

**Comment by elgohr** [comment]
Regarding the timeline I would agree.
Regarding the logger and in context of SBOMs I would see it as a problem if every dependency would add their favorite logging framework (version) to the game. Today I could write a wrapper on my own - but I can’t remove the dependency.

**Comment by blgm** [comment]
Hi @elgohr , with Go 1.22 likely to be released soon, I've created PR #292 which replaces `lager` with `slog`. I think it's inline with what you were suggesting. I'd be very interested in any feedback or suggestions that you have.
