### ISSUE TITLE
http request context handling

### ISSUE THREAD

**Issue by lwoydziak** [pivotal-cf/brokerapi#29]
The http request in golang has an attached context that is used to determine if client abandoned request. Some brokers make long running and/or retryable operations and could cancel them in the case that the client abandons the request. 

Please pass along this information to the callbacks because it will make for a more complete/production ready SDK.

**Comment by lwoydziak** [comment]
Please let me know if you require a sample implementation.

**Comment by avade** [comment]
@lwoydziak do you have an example of when the Cloud Controller would abandon a request? Long running operations are usually handled by async operations. 

The timeout for sync operations is 180 seconds, is this the use case you are thinking of? Being able to know when CC times out and being able to cancel the broker operation?

**Comment by julian-hj** [comment]
@avade:  It seems to me that the request could terminate for any network failure--not just when the CC times out.  So what should the broker do in the case where the http request terminated (for whatever reason)?  If we have the context object, then the broker can decide how to handle it.  If we don't, then it will carry on to complete the operation, which is probably not the right thing.

Does that make sense?

Thanks,
-Julian

**Comment by avade** [comment]
Makes sense, thanks for the explanation.

We would welcome a PR for this feature @lwoydziak

**Comment by lwoydziak** [comment]
See https://github.com/pivotal-cf/brokerapi/pull/30

**Comment by lwoydziak** [comment]
Close as pull request addresses this.
