### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by jmcarp** [pivotal-cf/brokerapi#34]
I noticed that there have been a few minor breaking changes lately--would you all be open to using semantic versioning and tagging releases so that users can get a better sense of what's changing?

**Comment by avade** [comment]
Hi @jmcarp - yes we can start semver tagging the package, it's something we have been meaning to do for awhile (thanks for the reminder!).

I hope these are the last of the breaking changes for now. We do have a planned interface refactor planned, but we will be raising a PR for community review / feedback.

**Comment by x6j8x** [comment]
@avade Any news on this?

**Comment by deniseyu** [comment]
@jmcarp @x6j8x yep - @kieron-pivotal has tagged the latest release now. Let us know if you have any problems consuming them by github tags.
