### ISSUE TITLE
Types in details structs are different

### ISSUE THREAD

**Issue by joek** [pivotal-cf/brokerapi#36]
Hi,
as you might have ssen I opend a pull request, which was not done so far. https://github.com/pivotal-cf/brokerapi/pull/35

What I like to know is, which direction should we go. Should all the *Details Structs have a RawParameteres field, should the PrivisionDetails struct be changed back to a map type Parameters field or should everything stay as it is ;-)

Cheers
Johannes

**Comment by avade** [comment]
Thanks for raising the @joek.

The team are going to discuss this soon and we will get back to you with an answer!

**Comment by Samze** [comment]
Hey @joek Thanks for submitting the PR.

You covered three changes in #35. Would you mind submitting three separate PRs for each? It's just a bit cleaner.

1. Regarding the `RawParameters` inconsistency, we agree that it would be best if the `BindDetails/UpdateDetails` had a `RawParameters` field with type `json.RawMessage`.
1. With regards to the new errors you introduced in #35, what's the point of having them if the broker api code doesn't check for them (i.e. https://github.com/pivotal-cf/brokerapi/blob/master/api.go#L102 for `update` and https://github.com/pivotal-cf/brokerapi/blob/master/api.go#L255 for `bind`)? What do you think these errors should translate to in HTTP codes? It does not seem that the [broker spec](https://docs.cloudfoundry.org/services/api.html#updating_service_instance) accounts for them at the moment.
1. Your changes regarding `LastOperationState` in `LastOperationResponse` look good.

And yes, please run (and fix) the tests. :heart_eyes_cat:

-- @Samze & @st3v

**Comment by joek** [comment]
@Samze thanks for your response. I will send pull requests as soon as I cleaned up my messy changes and added testing ;-)
