### ISSUE TITLE
Allow returning custom error status codes and responses

### ISSUE THREAD

**Issue by jmcarp** [pivotal-cf/brokerapi#37]
At the moment, brokerapi users can return predefined error types to control status codes and response bodies: `ErrRawParamsInvalid`, `ErrInstanceAlreadyExists`, etc. Other errors always throw a 500. What do you think about accepting an error type that would allow developers more control over error responses, like this:

```go
type APIError struct {
	StatusCode int
	Body map[string]interface{}
}

func (e APIError) String() string {
	body, err := json.Marshal(e.Body)
	if err != nil {
		return "Unknown error"
	}
	return string(body)
}
```

Then we'd be able to move long `switch` statements like https://github.com/pivotal-cf/brokerapi/blob/master/api.go#L103-L128 into a series of error instances, and users would be able to customize errors. WDYT?

**Comment by Samze** [comment]
Hey @jmcarp,

Sorry for the delayed response, I think adding support for custom http codes is great idea.

The broker spec states:
` Broker failures beyond the scope of the well-defined HTTP response codes listed above (like 410 on delete) should return an appropriate HTTP response code.`

Would you be willing to submit a PR?

Thanks,
Sam
