### ISSUE TITLE
How to use brokerapi for multiple services

### ISSUE THREAD

**Issue by bingosummer** [pivotal-cf/brokerapi#43]
If I want to write a service broker for multiple services (e.g. mysql and redis), is it doable?

From my understanding, since the route `/v2/service_instances/:instance_id` doesn't contain `service_id`, so I can't define two brokers like this:
```
mysqlBrokerAPI := brokerapi.New(mysqlServiceBroker, brokerLogger, brokerCredentials)
http.Handle("/route-for-mysql", mysqlBrokerAPI)
redisBrokerAPI := brokerapi.New(redisServiceBroker, brokerLogger, brokerCredentials)
http.Handle("/route-for-redis", redisBrokerAPI)
```

It seems that I need to write different logics for different service in the `Provision`. Is there any guidance for multiple services?
Thanks.

**Comment by jamesjoshuahill** [comment]
Hi @bingosummer, it is possible to define multiple services in a service broker catalog. You will need to implement the `ServiceBroker` interface and then on a provision request the `Provision` function will be passed `ProvisionDetails` that include the `ServiceID`. Then you can write the logic for each service that you require. It may be simpler to maintain a service broker for each service.

**Comment by bingosummer** [comment]
Thanks @jamesjoshuahill . Makes sense.
