### ISSUE TITLE
200OK response for Bind Service Calls is not returned from the current API code

### ISSUE THREAD

**Issue by PradeepGunasekar** [pivotal-cf/brokerapi#44]
HI Team - the documentation for CF mentions the Bind call to return 200OK when same instance,bindingId and Parameters are passed. but we are unable to get the response from the broker api code.
was this removed for a reason or am i missing something? pls Advise

**Comment by mattmcneeney** [comment]
@avade Is this a known issue with the BrokerAPI?

**Comment by avade** [comment]
@PradeepGunasekar This behaviour is not currently supported in the BrokerAPI package. The brokers we create trust that the platform will only send the request once.

We would be interested to see a PR to add support this behaviour and are open to discussing the design before.

**Comment by PradeepGunasekar** [comment]
Thanks @avade , i would be more interested to check the possible options for getting 200OK response and if those scenarios occur then open to contribute to the design and developments. 
Let me know if this issue is prioritized for discussion.

**Comment by mattmcneeney** [comment]
Hey @PradeepGunasekar Is this still an issue for you? We're aware that we never currently return a 200OK in this situation, and so we are not strictly adhering to the specification.

cc @kieron-pivotal for technical input on how hard it would be to improve the interface to support this (I think today we only support returning a 200 or 4xx error).

**Comment by PradeepGunasekar** [comment]
currently we kept this Application on HOLD so would not need this feature, thank you.
