### ISSUE TITLE
Semver and Releases

### ISSUE THREAD

**Issue by cholick** [pivotal-cf/brokerapi#61]
As of filing this, the latest release is `v3.0.2`, but the semver tags go up through `v3.0.7`. Should consumers of this package use the explicitly released version or the latest semver tag?

**Comment by winnab** [comment]
Hi @cholick,

We've just added a v4.0.0 release, which includes work for the OSBAPI 2.14 spec and relates to the v3.0.3 tag. The tags between v3.0.3 and v3.0.7 were created for internal use. In the future, we plan to be more explicit and less confusing about creating releases. Thanks for bringing this to our attention, and let us know if you have additional thoughts.

Winna and @kieron-pivotal
