### ISSUE TITLE
Add support for dynamic authentication

### ISSUE THREAD

**Issue by fabianlindfors** [pivotal-cf/brokerapi#68]
Currently the library only seems to support static credentials for authentication. We're developing a broker where we want to let users pass API credentials through the broker basic auth.

I'm thinking that `BrokerCredentials` in the `New` function could be replaced with an interface with a single function for validation. `BrokerCredentials` could then implement this interface making the change backwards compatible. The passed credentials would probably have to be accessible in all the `ServiceBroker` functions, perhaps as part of the `details` parameter.

**Comment by winnab** [comment]
Hi @fabianlindfors! Thanks for reaching out. Our team has a few things on at the moment, and I don't want to block. Would you like to do a PR for the tests/implementation that you're thinking of and we can review?

**Comment by mszostok** [comment]
Hi @winnab  can I take this?
IMO the best option will be to do that with the functional option pattern, do you agree?

**Comment by FelisiaM** [comment]
Hi @mszostok & @fabianlindfors 

Apologies for the delayed response. 
We are wondering if you are still interested in this change? We would be happy to review a PR if so.

Thanks
Felisia & @kirederik

**Comment by fabianlindfors** [comment]
Hi, @FelisiaM!

I'm no longer involved in this project but we were able to work around the issue using some context tricks. Feel free to close this issue unless it's something you still want to implement.
