### ISSUE TITLE
Reusing brokerapi middlewares

### ISSUE THREAD

**Issue by desislavaa** [pivotal-cf/brokerapi#83]
I am working on a service broker that is supposed to do audit logging. In order for us to achieve that we need to use custom authentication middleware and later [`AttachRoutes`](https://github.com/pivotal-cf/brokerapi/blob/master/api.go#L50) to our router.

Since adding reusable code in `pkg` folder is commonly used but not considered a standard in Go, my question is, can we attach the `brokerapi` middlewares instead of implementing our own? Is this functionality supposed to be reused?

**Comment by kirederik** [comment]
Hi @desislavaa,

Just to guarantee that we understand your question: 

You want to implement a custom auth middleware and reuse all the other broker middlewares  (as defined [here](https://github.com/pivotal-cf/brokerapi/blob/cf0dcc39e8bcb0a904b4e1cac9263603c442aa9e/api.go#L41-L45)). That means that in your code you would have a function similar to `brokerapi.New`, just changing the auth middleware to your custom implementation. Your question is whether or not this is a good idea/recommended?

If so, yes. Feel free to reuse the broker middlewares. That's actually why we have `AttachRoutes` as a public method. 

We would also be curious to hear if you have any ideas on how to make it easier for users of the brokerapi to provide custom middlewares.

Let us know if you need further help.

Thanks!

**Comment by desislavaa** [comment]
That was exactly my question, thank you for the quick response!

We thought about a wrapper function of `New`, let's say `NewWithAuthorizer`, where the user can pass an implementation of an `Authorizer` interface or something like that, but that would work only for our particular use case (however, if you like the idea, we'll be glad to contribute it).

If we pass user-provided middlewares instead, a problem would be their order, so the already present approach with adding them manually looks more suitable.
Adding them at the end is also possible at the moment, since `New` returns a router.
If we think of anything that could possibly solve that, we'll be happy to share it.

Thanks again!
